const products = [
  {
    id: '1',
    src: [
      '/images/produto1.png',
      '/images/produto1.png',
      '/images/produto1.png',
      '/images/produto1.png',
    ],
    tamanho: ['P', 'M', 'G'],
    nome: 'Produto 1',
    descrição: 'Descrição do Produto 1',
    preço_original: 299.90,
    preço_promocional: 199.90,
    parcelamento: 'Em até 3x',
    parcelamento_valor: 'R$ 66.63',
    flags: ['Novo', 'Promoção'],
  },
  {
    id: '2',
    src: [
      '/images/produto2.png',
      '/images/produto2.png',
      '/images/produto2.png',
      '/images/produto2.png',
    ],
    tamanho: ['P', 'M', 'G'],
    nome: 'Produto 2',
    descrição: 'Descrição do Produto 2',
    preço_original: 399.90,
    preço_promocional: 299.90,
    parcelamento: 'Em até 3x de',
    parcelamento_valor: 'R$ 99.97',
    flags: ['Novo'],
  },
  {
    id: '3',
    src: [
      '/images/produto3.png',
      '/images/produto3.png',
      '/images/produto3.png',
      '/images/produto3.png',
    ],
    tamanho: ['P', 'M', 'G'],
    nome: 'Produto 3',
    descrição: 'Descrição do Produto 3',
    preço_original: 199.90,
    preço_promocional: 149.90,
    parcelamento: 'Em até 3x de',
    parcelamento_valor: 'R$ 49.97',
    flags: ['Promoção'],
  },
  {
    id: '4',
    src: [
      '/images/produto4.png',
      '/images/produto4.png',
      '/images/produto4.png',
      '/images/produto4.png',
    ],
    tamanho: ['P', 'M', 'G'],
    nome: 'Produto 4',
    descrição: 'Descrição do Produto 4',
    preço_original: 499.90,
    preço_promocional: 399.90,
    parcelamento: 'Em até 3x de',
    parcelamento_valor: 'R$ 133.30',
    flags: [],
  },
  {
    id: '5',
    src: [
      '/images/produto5.png',
      '/images/produto5.png',
      '/images/produto5.png',
      '/images/produto5.png',
    ],
    tamanho: ['P', 'M', 'G'],
    nome: 'Produto 5',
    descrição: 'Descrição do Produto 5',
    preço_original: 299.90,
    preço_promocional: 249.90,
    parcelamento: 'Em até 3x de',
    parcelamento_valor: 'R$ 83.30',
    flags: ['Novo', 'Promoção'],
  },
  {
    id: '6',
    src: [
      '/images/produto6.png',
      '/images/produto6.png',
      '/images/produto6.png',
      '/images/produto6.png',
    ],
    tamanho: ['P', 'M', 'G'],
    nome: 'Produto 6',
    descrição: 'Descrição do Produto 6',
    preço_original: 599.90,
    preço_promocional: 499.90,
    parcelamento: 'Em até 3x de',
    parcelamento_valor: 'R$ 166.63',
    flags: [],
  },
];

export default products;
